# Generated by Django 3.1.1 on 2020-09-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_on', '-pk']},
        ),
        migrations.AddField(
            model_name='video',
            name='can_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='can_duet_react',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='only_friends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='visible',
            field=models.BooleanField(default=True, help_text='For admin purposes'),
        ),
    ]
