# Generated by Django 3.1.1 on 2020-09-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20200907_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.video')),
            ],
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['title'], name='feed_tag_title_i_d34990_idx'),
        ),
    ]
