# Generated by Django 3.1.1 on 2020-09-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20200907_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['name', 'artist'], name='feed_music_name_0b5305_idx'),
        ),
    ]
