# Generated by Django 3.1.1 on 2020-11-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20200913_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='media_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Image', 'Image')], default='Image', max_length=50),
        ),
    ]
