# Generated by Django 3.1.1 on 2020-11-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_video_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='media_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Image', 'Image')], default='Image', max_length=50),
        ),
    ]
