# Generated by Django 3.1.1 on 2020-11-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20201115_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='media_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Image', 'Image')], default='Image', max_length=50),
        ),
    ]
