# Generated by Django 3.1.1 on 2020-09-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0004_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.video')),
            ],
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['title'], name='tags_tag_title_i_485b05_idx'),
        ),
    ]
