# Generated by Django 3.1.1 on 2020-09-07 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_delete_tag'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tag',
            name='tags_tag_title_i_485b05_idx',
        ),
        migrations.AddField(
            model_name='tag',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.video'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(default='Kendall', max_length=30),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['title'], name='tags_tag_title_fb756e_idx'),
        ),
    ]
