# Generated by Django 3.1.1 on 2020-11-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201111_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsetting',
            name='store_currency',
            field=models.CharField(choices=[('eur', 'Eur'), ('dollars', 'Dollars')], default='eur', max_length=10),
        ),
    ]
